# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fc6a6309d088b866be1206204a46098e505613b2e19fa438ea3a6b54f3307960416a7fcf52cd0e812037fe9c7e69d5d3b068b029ede7a669ab8d12d18995210

test:
  secret_key_base: e0840ba6fee5ad51b92a90b33ca9ecb5afee43a457acb4c51aa49d6d99bc7497628b3bfeeb642af01e3cdae66f1dca308d0bca13bbb69f7a207bfa4f84774f47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
